name: Howard Lucas Photographer
favicon: null
layout_spectrum: 0.5343453285750002
typography_spectrum: 0.13215442094951868
title: 'Photographer | Wedding | Lifestyle | Beauty'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eaeae8'
    - '#2f3325'
    - '#6d7342'
    - '#d2b6a3'
    - '#d1a622'
  brandStrength: 0
  lightness: 0.04478361876681447
  saturation: 0.786105346865952
  rhythmicContrast: 0.6400162968784571
purpose: []
