name: Howard Lucas Photographer
favicon: null
layout_spectrum: 0.5343453285750002
typography_spectrum: 0.13215442094951868
title: 'Photographer | Wedding | Lifestyle | Beauty'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.48474588547833264
  lightness: 0.04478361876681447
  saturation: 0.786105346865952
  rhythmicContrast: 0.6400162968784571
purpose: []
